# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
#PS1='%F{green}%n@%m%f:%F{magenta}%~%f  '
#PS1='%F{green}%n@slalom%f:%F{magenta}%~%f  '

MY_APPLE_ICON=""  # https://emojipedia.org/apple-logo
# Fix Apple logo to render properly in Ghostty
# TERM_PROGRAM = ghostty, vscode, Apple_Terminal
if [[ "$TERM_PROGRAM" = "ghostty" ]]; then
    # https://www.nerdfonts.com/cheat-sheet
    MY_APPLE_ICON=""
fi

autoload -Uz vcs_info
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '%F{red}*'   # display this when there are unstaged changes
zstyle ':vcs_info:*' stagedstr '%F{yellow}+'  # display this when there are staged changes
zstyle ':vcs_info:*' actionformats '%F{5}[%F{2}%b%F{3}|%F{1}%a%c%u%F{5}]%f '
zstyle ':vcs_info:*' formats '%F{5}[%F{2}%b%c%u%F{5}]%f '
zstyle ':vcs_info:svn:*' branchformat '%b'
zstyle ':vcs_info:svn:*' actionformats '%F{5}[%F{2}%b%F{1}:%F{3}%i%F{3}|%F{1}%a%c%u%F{5}]%f '
zstyle ':vcs_info:svn:*' formats '%F{5}[%F{2}%b%F{1}:%F{3}%i%c%u%F{5}]%f '
zstyle ':vcs_info:*' enable git cvs svn

theme_precmd () {
    vcs_info
}

setopt prompt_subst
PROMPT='%~/ %{$reset_color%}${vcs_info_msg_0_}%{$reset_color%}${MY_APPLE_ICON} '

autoload -U add-zsh-hook
add-zsh-hook precmd theme_precmd

# Hoembrew configuration
# https://docs.brew.sh/Analytics
export HOMEBREW_NO_ANALYTICS=1
# https://docs.brew.sh/Manpage
export HOMEBREW_NO_ENV_HINTS="true"

# Use brewed curl
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Python
export PATH="$HOME/Library/Python/3.11/bin:$PATH"

# Use brewed Go
export PATH="$HOME/go/bin:$PATH"

# Use brewed Ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include $CPPFLAGS"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"

# Android Studio
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# Flutter
export PATH="$HOME/flutter/bin:$PATH"
# CocoaPods (for Flutter)
export GEM_HOME="$HOME/.gem"
export PATH="$GEM_HOME/bin:$PATH"
export PATH="$GEM_HOME/ruby/3.2.0/bin:$PATH"

# Ansible vault password
export ANSIBLE_VAULT_PASSWORD_FILE="/Users/nils/.ansible/ansible-vault-secret-password"

# Enable autocomplete
autoload -Uz compinit && compinit

# gcloud autocomplete
source /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Use brewed Perl
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

# Use the Fuck (https://github.com/nvbn/thefuck)
eval $(thefuck --alias)

# Use brewed Java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include $CPPFLAGS"

# VS Code
alias vsc='code .'

# Git
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git#aliases
alias g='git'
alias gl='git pull'
alias gp='git push'
alias gsh='git show'
alias gcam='git commit --all --message'

alias lz='lazygit'

# Podman 🦭
alias docker='podman'

# Terraform
alias tf='terraform'
alias tfa='terraform apply'
alias tfc='terraform console'
alias tfd='terraform destroy'
alias tff='terraform fmt'
alias tfi='terraform init'
alias tfim='terraform init -migrate'
alias tfiu='terraform init -upgrade'
alias tfo='terraform output'
alias tfp='terraform plan'
alias tfr='terraform refresh'
alias tfs='terraform state'
alias tfsh='terraform show'
alias tft='terraform test'
alias tfv='terraform validate'

# Aliases
alias show-all-files-on='defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder'
alias show-all-files-off='defaults write com.apple.finder "AppleShowAllFiles" -bool "false" && killall Finder'
alias ls='ls --color'
alias ll='ls -lah'
alias plackup='plackup --host="127.0.0.1"'
alias gcosts='/Users/nils/Developer/google-cloud-pricing-cost-calculator/gcosts/gcosts --pricing /Users/nils/Developer/google-cloud-pricing-cost-calculator/build/pricing.yml'
alias archive-dl='wget -r --no-parent'