# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
#PS1='%F{green}%n@%m%f:%F{magenta}%~%f  '
#PS1='%F{green}%n@slalom%f:%F{magenta}%~%f  '

# TERM_PROGRAM = ghostty, vscode, Apple_Terminal
EZA_ICONS=""
if [[ "$TERM_PROGRAM" = "ghostty" ]]; then
  # https://starship.rs/config/
  eval "$(starship init zsh)"
  # https://www.nerdfonts.com/cheat-sheet
  EZA_ICONS="--icons"
else
  MY_APPLE_ICON="" # https://emojipedia.org/apple-logo
  setopt prompt_subst
  PROMPT='%~/ ${MY_APPLE_ICON} '
fi

# eza Dracula colors
# https://draculatheme.com/eza
export EZA_COLORS="\
uu=36:\
uR=31:\
un=35:\
gu=37:\
da=2;34:\
ur=34:\
uw=95:\
ux=36:\
ue=36:\
gr=34:\
gw=35:\
gx=36:\
tr=34:\
tw=35:\
tx=36:\
xx=95:"

# Hoembrew configuration
# https://docs.brew.sh/Analytics
export HOMEBREW_NO_ANALYTICS=1
# https://docs.brew.sh/Manpage
export HOMEBREW_NO_ENV_HINTS="true"

# Use brewed curl
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Python
export PATH="$HOME/Library/Python/3.11/bin:$PATH"

# Use brewed Go
export PATH="$HOME/go/bin:$PATH"

# Use brewed Ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include $CPPFLAGS"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"

# Android Studio
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# Flutter
export PATH="$HOME/flutter/bin:$PATH"
# CocoaPods (for Flutter)
export GEM_HOME="$HOME/.gem"
export PATH="$GEM_HOME/bin:$PATH"
export PATH="$GEM_HOME/ruby/3.2.0/bin:$PATH"

# Use brewed Java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include $CPPFLAGS"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/nils/.cache/lm-studio/bin"
# End of LM Studio CLI section

# Ansible vault password
export ANSIBLE_VAULT_PASSWORD_FILE="/Users/nils/.ansible/ansible-vault-secret-password"

# Enable autocomplete
autoload -Uz compinit && compinit
# Use Caraspace (https://carapace.sh/) for autocomplete
export CARAPACE_BRIDGES='zsh'
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)

# Enable fzf (command-line fuzzy finder) shell integration
# https://junegunn.github.io/fzf/shell-integration/
# https://draculatheme.com/fzf
export FZF_DEFAULT_OPTS='--height 40% --layout reverse --border --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
source <(fzf --zsh)

# Use brewed Perl
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

# Use the Fuck (https://github.com/nvbn/thefuck)
eval $(thefuck --alias)

# VS Code
alias vsc='code .'

# Git
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git#aliases
alias g='git'
alias gl='git pull'
alias gp='git push'
alias gsh='git show'
alias gcam='git commit --all --message'
alias yolo='git commit -am "$(curl -s https://whatthecommit.com/index.txt)"'

alias lz='lazygit'

# Podman 🦭
alias docker='podman'

# Terraform
alias tf='terraform'
alias tfa='terraform apply'
alias tfc='terraform console'
alias tfd='terraform destroy'
alias tff='terraform fmt'
alias tfi='terraform init'
alias tfim='terraform init -migrate'
alias tfiu='terraform init -upgrade'
alias tfo='terraform output'
alias tfp='terraform plan'
alias tfr='terraform refresh'
alias tfs='terraform state'
alias tfsh='terraform show'
alias tft='terraform test'
alias tfv='terraform validate'

# Aliases
alias archive-dl='wget -r --no-parent'
alias gcloud-auth-app='gcloud auth application-default login --no-launch-browser'
alias gcloud-auth='gcloud auth login --no-launch-browser'
alias gcosts='/Users/nils/Developer/google-cloud-pricing-cost-calculator/gcosts/gcosts --pricing /Users/nils/Developer/google-cloud-pricing-cost-calculator/build/pricing.yml'
alias ll='ls -lah'
alias ls='ls --color'
alias lsa="eza --all --long $EZA_ICONS"
alias lst="eza --all --long --tree --level=3 --ignore-glob=.git $EZA_ICONS"
alias myip='curl -4 --silent http://whatismyip.akamai.com/'
alias plackup='plackup --host="127.0.0.1"'
alias show-all-files-off='defaults write com.apple.finder "AppleShowAllFiles" -bool "false" && killall Finder'
alias show-all-files-on='defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder'

# Load API keys
if [ -f "$HOME/.api_keys" ]; then
    source "$HOME/.api_keys"
fi
