# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
PS1='%F{green}%n@%m%f:%F{magenta}%~%f  '

# Hoembrew configuration
# https://docs.brew.sh/Analytics
export HOMEBREW_NO_ANALYTICS=1
# https://docs.brew.sh/Manpage
export HOMEBREW_NO_ENV_HINTS="true"

# Use brewed curl
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Python
export PATH="$HOME/Library/Python/3.11/bin:$PATH"

# Use brewed Go
export PATH="$HOME/go/bin:$PATH"

# Use brewed Ruby
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"

# Android Studio
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# Flutter
export PATH="$HOME/flutter/bin:$PATH"
# CocoaPods (for Flutter)
export GEM_HOME="$HOME/.gem"
export PATH="$GEM_HOME/bin:$PATH"
export PATH="$GEM_HOME/ruby/3.2.0/bin:$PATH"

# Ansible vault password
export ANSIBLE_VAULT_PASSWORD_FILE="/Users/nils/.ansible/ansible-vault-secret-password"

# Enable autocomplete
autoload -Uz compinit && compinit

# gcloud autocomplete
source /opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Use brewed Perl
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"

# Use brewed Java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# Aliases
alias show-all-files-on='defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder'
alias show-all-files-off='defaults write com.apple.finder "AppleShowAllFiles" -bool "false" && killall Finder'
alias ls='ls --color'
alias ll='ls -lah'
alias plackup='plackup --host="127.0.0.1"'
alias gcosts='/Users/nils/Developer/google-cloud-pricing-cost-calculator/gcosts/gcosts --pricing /Users/nils/Developer/google-cloud-pricing-cost-calculator/build/pricing.yml'